/**
 * seed-swiss.ts — Swiss tournament test scenario.
 *
 * Creates a realistic mid-tournament state:
 *   - 28 male + 22 female players (real Colinas Invitacional names)
 *   - 6 Swiss rounds mapped to schedule_weeks
 *   - Rounds 1–3: fully played — scores inserted, status = completed
 *   - Round  4:   published (current week) — matches pending, no scores
 *   - Rounds 5–6: draft (future rounds) — matches created, no scores
 *
 * Pairings and scores are generated by simulateSwiss() from lib/formats so
 * the data is internally consistent (no rematches in early rounds, realistic
 * set scores, standings follow naturally from results).
 *
 * Usage: npm run seed-swiss
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { sql } from "@vercel/postgres";
import { simulateSwiss, SWISS_ROUNDS } from "@/lib/formats";
import type { Standing } from "@/lib/db";

/* ── Player names (real Colinas Invitacional roster) ── */

const MALE_NAMES = [
	"Francisco Chavez", "Francisco Madrid", "Tasuko Sato", "Jesus Salomon",
	"Yuichi Castro", "Pablos Flores", "Constantino Dimopulos", "Miguel Leon",
	"Edel Flores", "Raul Camacho", "Roberto", "Daniel Elizabeth",
	"Fernando Franco", "Olga Perez", "Angel Conde", "Jesus Alvarez",
	"Juan Pablo Jr", "Juan Pablo", "Jorge Inzunza", "Daniel Ofe",
	"Raul Camacho Jr", "Fernando Esquer", "Francisco Esquer", "Ernesto Esquer",
	"Checo Padilla", "Luis Enrique Parra", "Juan M Sato", "Santiago Sato",
];

const FEMALE_NAMES = [
	"Daniela Rochin", "Liz Montaño", "Carolina Parra", "Lucia",
	"Sara Tirado", "Celia", "Italia", "Silvia",
	"Scarlett", "Karina", "Susana", "Elizabeth",
	"Argelia", "Lorena", "Ale Luna", "Ofelia",
	"Naomi Bernal", "Fernanda Orozco", "Wendy", "Mia",
	"Cristina Padilla", "Emma Parra",
];

/* ── Round / week schedule ── */

const ROUND_CONFIG = [
	{ weekNum: 1, start: "2026-04-06", end: "2026-04-12", status: "completed", playedDate: "2026-04-08" },
	{ weekNum: 2, start: "2026-04-13", end: "2026-04-19", status: "completed", playedDate: "2026-04-15" },
	{ weekNum: 3, start: "2026-04-20", end: "2026-04-26", status: "completed", playedDate: "2026-04-22" },
	{ weekNum: 4, start: "2026-04-27", end: "2026-05-03", status: "published", playedDate: null },
	{ weekNum: 5, start: "2026-05-04", end: "2026-05-10", status: "draft",     playedDate: null },
	{ weekNum: 6, start: "2026-05-11", end: "2026-05-17", status: "draft",     playedDate: null },
] as const;

/* ── Helpers ── */

function makeStandings(ids: number[], names: string[], category: "M" | "F"): Standing[] {
	return ids.map((id, i) => ({
		id,
		name: names[i],
		category,
		played: 0,
		won: 0,
		lost: 0,
		pending: 0,
		sets_won: 0,
		sets_lost: 0,
	}));
}

/* ── Main ── */

async function seed() {
	console.log("\n🗑️  Limpiando datos existentes...");

	await sql`DELETE FROM matches;`;
	await sql`DELETE FROM player_availability;`;
	await sql`DELETE FROM schedule_weeks;`;
	await sql`DELETE FROM audit_logs;`;
	await sql`DELETE FROM players;`;

	/* Reset auto-increment sequences */
	await sql`ALTER SEQUENCE players_id_seq RESTART WITH 1;`;
	await sql`ALTER SEQUENCE matches_id_seq RESTART WITH 1;`;
	await sql`ALTER SEQUENCE schedule_weeks_id_seq RESTART WITH 1;`;
	await sql`ALTER SEQUENCE player_availability_id_seq RESTART WITH 1;`;
	await sql`ALTER SEQUENCE audit_logs_id_seq RESTART WITH 1;`;

	/* ── Players ── */

	console.log(`\n👨 Insertando ${MALE_NAMES.length} jugadores masculinos...`);
	const maleIds: number[] = [];
	for (const name of MALE_NAMES) {
		const { rows } = await sql`
			INSERT INTO players (name, category) VALUES (${name}, 'M') RETURNING id;
		`;
		maleIds.push(rows[0].id);
	}

	console.log(`👩 Insertando ${FEMALE_NAMES.length} jugadoras femeninas...`);
	const femaleIds: number[] = [];
	for (const name of FEMALE_NAMES) {
		const { rows } = await sql`
			INSERT INTO players (name, category) VALUES (${name}, 'F') RETURNING id;
		`;
		femaleIds.push(rows[0].id);
	}

	console.log(`   ✅ ${maleIds.length + femaleIds.length} jugadores creados.`);

	/* ── Schedule weeks ── */

	console.log("\n📅 Creando semanas (rondas)...");
	const weekIds: number[] = [];
	for (const cfg of ROUND_CONFIG) {
		const { rows } = await sql`
			INSERT INTO schedule_weeks (week_number, start_date, end_date, status)
			VALUES (${cfg.weekNum}, ${cfg.start}, ${cfg.end}, ${cfg.status})
			RETURNING id;
		`;
		weekIds.push(rows[0].id);
		console.log(`   Ronda ${cfg.weekNum} (${cfg.status}): ${cfg.start} → ${cfg.end}  [id=${rows[0].id}]`);
	}

	/* ── Simulate Swiss rounds ── */

	/*
	 * Use fixed seeds so the scenario is reproducible.
	 * Male seed: 2026, Female seed: 2027.
	 * Both 28M and 22F are even counts so no byes will occur.
	 */
	const maleRounds  = simulateSwiss(makeStandings(maleIds,   MALE_NAMES,   "M"), 2026);
	const femaleRounds = simulateSwiss(makeStandings(femaleIds, FEMALE_NAMES, "F"), 2027);

	/* ── Insert matches ── */

	console.log("\n🎾 Insertando partidos...");
	let totalMatches = 0;

	for (let r = 0; r < SWISS_ROUNDS; r++) {
		const cfg    = ROUND_CONFIG[r];
		const weekId = weekIds[r];
		const played = cfg.status === "completed";

		const mRound = maleRounds[r];
		const fRound = femaleRounds[r];

		/* Male matches */
		for (const match of mRound.matches) {
			if (played) {
				await sql`
					INSERT INTO matches
						(player_a_id, player_b_id, category, week_id, phase, status, score, date_played)
					VALUES
						(${match.playerA.id}, ${match.playerB.id}, 'M', ${weekId},
						 'round_robin', 'jugado', ${match.score}, ${cfg.playedDate});
				`;
			} else {
				await sql`
					INSERT INTO matches
						(player_a_id, player_b_id, category, week_id, phase, status)
					VALUES
						(${match.playerA.id}, ${match.playerB.id}, 'M', ${weekId},
						 'round_robin', 'pendiente');
				`;
			}
			totalMatches++;
		}

		/* Female matches */
		for (const match of fRound.matches) {
			if (played) {
				await sql`
					INSERT INTO matches
						(player_a_id, player_b_id, category, week_id, phase, status, score, date_played)
					VALUES
						(${match.playerA.id}, ${match.playerB.id}, 'F', ${weekId},
						 'round_robin', 'jugado', ${match.score}, ${cfg.playedDate});
				`;
			} else {
				await sql`
					INSERT INTO matches
						(player_a_id, player_b_id, category, week_id, phase, status)
					VALUES
						(${match.playerA.id}, ${match.playerB.id}, 'F', ${weekId},
						 'round_robin', 'pendiente');
				`;
			}
			totalMatches++;
		}

		/* Report byes (shouldn't occur with even counts) */
		if (mRound.bye)  console.log(`   ⚠️  Ronda ${r + 1}: BYE masculino  → ${mRound.bye.name}`);
		if (fRound.bye)  console.log(`   ⚠️  Ronda ${r + 1}: BYE femenino   → ${fRound.bye.name}`);

		console.log(
			`   Ronda ${r + 1} [${cfg.status.padEnd(9)}]: ` +
			`${mRound.matches.length}M + ${fRound.matches.length}F = ` +
			`${mRound.matches.length + fRound.matches.length} partidos` +
			(played ? `  (${cfg.playedDate})` : "  (pendiente)")
		);
	}

	/* ── Summary ── */

	console.log("\n────────────────────────────────────────────────");
	console.log(`✅ Seed Swiss completo:`);
	console.log(`   ${maleIds.length} jugadores masculinos`);
	console.log(`   ${femaleIds.length} jugadoras femeninas`);
	console.log(`   ${SWISS_ROUNDS} rondas (semanas)`);
	console.log(`   ${totalMatches} partidos (${ROUND_CONFIG.filter(c => c.status === "completed").length * (maleRounds[0].matches.length + femaleRounds[0].matches.length)} jugados, resto pendientes)`);
	console.log("\n   Rondas 1-3:  jugadas  ✅");
	console.log("   Ronda  4:    publicada 📢  (esta semana)");
	console.log("   Rondas 5-6:  borrador  📋  (futuras)");
}

seed().catch((err) => {
	console.error("\n❌ Error:", err);
	process.exit(1);
});
